### ISSUE TITLE
Skip and log invalid loadouts

### ISSUE THREAD

**Issue by icabiltes21** [dcs-liberation/dcs_liberation#2320]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2652273486

### Description

After campaign start, with all player assist on. Trying to edit the package with F18s on it shows this error

![image](https://user-images.githubusercontent.com/62088555/179077060-b309a95e-f72a-4dc7-8a63-5ba2e673951c.png)

sorry I'm new to reporting

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9115173/liberation.log)

liberation file
[here.zip](https://github.com/dcs-liberation/dcs_liberation/files/9115180/here.zip)

**Comment by Raffson** [comment]
Do you have a custom loadout with decoys? If so, try deleting it.

**Comment by Starfire13** [comment]
Yeah, this would be because you're using the new Hornet TALDs.

**Comment by DanAlbert** [comment]
Is the loadout one that's being used by liberation? If yes, an error is what I'd expect, but we should probably improve that message, since we've seen quite a few forms of this bug.

If it _isn't_, and it's actually the case that players can't have _any_ loadouts with weapons that pydcs doesn't know about, we should fix that to just ignore (but log) loadouts that we can't use. I wasn't sold on that for the case where loadouts we're using weapons that didn't exist in DCS any more, but if loadouts for current versions of DCS are causing liberation to fail even when those loadouts aren't used, that should definitely be fixed.

**Comment by Raffson** [comment]
> Is the loadout one that's being used by liberation? If yes, an error is what I'd expect, but we should probably improve that message, since we've seen quite a few forms of this bug.
> 
> If it _isn't_, and it's actually the case that players can't have _any_ loadouts with weapons that pydcs doesn't know about, we should fix that to just ignore (but log) loadouts that we can't use. I wasn't sold on that for the case where loadouts we're using weapons that didn't exist in DCS any more, but if loadouts for current versions of DCS are causing liberation to fail even when those loadouts aren't used, that should definitely be fixed.

It's a pydcs issue for sure, on one hand it has a scanner for payloads, but it relies on weapons data from the export. While working on the livery scanner, I realized something similar could be done for weapons and pylons in pydcs, which would in theory solve this problem for good. If an error would still occur, it's almost guaranteed to be an issue with the user's installation/mods.

Meanwhile if you want a quick patch I recommend using the `get` method of the dictionary and handle "None-returns" wherever `with_clsid`  is used (I find 4 cases with PyCharm). The actual "handling" in this case would be to simply skip the loadout in question. Aside from that I believe only 2 out of those 4 cases could cause problems, i.e. both occurrences in `game\ato\loadout.py`.

**Comment by icabiltes21** [comment]
> Do you have a custom loadout with decoys? If so, try deleting it.

that fixed it, does that mean I cant use them?


> Is the loadout one that's being used by liberation? If yes, an error is what I'd expect, but we should probably improve that message, since we've seen quite a few forms of this bug.
> 
Its a loadout I made in the mission editor, not the ones liberation have

**Comment by DanAlbert** [comment]
But if you named it appropriately Liberation will use it by default. That's how you customize the default loadouts. I assume that means you didn't do that?

**Comment by icabiltes21** [comment]
I did not, the loadout name that had the TALDS in them were called 4.AG 4xTALD

**Comment by Starfire13** [comment]
Liberation will load all loadouts you create in the mission editor, even ones without Liberation in the name.

**Comment by DanAlbert** [comment]
Yeah, we should fix that to ignore loadouts that can't be loaded.

**Comment by Raffson** [comment]
I still think it would be better to handle this is pydcs, but until then.....
