### ISSUE TITLE
Long airfield titles are cutting off the number of available aircraft

### ISSUE THREAD

**Issue by dimkzr** [dcs-liberation/dcs_liberation#552]
See the screenshot. Even with this window expanded, it's impossible to tell how many aircraft are available.

![Screenshot - Sat 12 Dec , 13_41_11](https://user-images.githubusercontent.com/16318490/101981746-14f4cc80-3c80-11eb-8b7f-473f75815fff.png)

Probably the easiest solution (to avoid expanding both the window and the dropdown, because there could be even longer titles) is to change format to [Number of aircraft]x at [Airfield title] > "3x at CVN-74 John C. Stennis"

**Comment by DanAlbert** [comment]
That's weird. Mine doesn't do that. Are you on 2.2? Maybe we fixed this in 2.3 already.

![image](https://user-images.githubusercontent.com/315852/101996260-97cc5600-3c85-11eb-8bf2-804f4a3f7028.png)

**Comment by dimkzr** [comment]
> Are you on 2.2? Maybe we fixed this in 2.3 already.

Yes, it seems so. I'm using 2.2.1.

Case closed then :-)

**Comment by DanAlbert** [comment]
Could also be something different between our configurations maybe, but that'd be weird.

**Comment by dimkzr** [comment]
I will test this in 2.3 release and re-open if necessary.

**Comment by dimkzr** [comment]
Sorry to say, but I'm still having this issue in 2.3.2

The "Create flight" window is very narrow by default (dunno why yours is so wide), and expanding it doesn't solve the problem.

![Screenshot - Mon 28 Dec , 04_32_55](https://user-images.githubusercontent.com/16318490/103183874-3089e500-48c6-11eb-8c48-b20420dbd977.png)

![Screenshot - Mon 28 Dec , 04_33_55](https://user-images.githubusercontent.com/16318490/103183878-354e9900-48c6-11eb-9f5f-ed72ad36c842.png)

**Comment by dimkzr** [comment]
I think I found the culprit.

The width of each dropdown is based on the width of a **first** element in said dropdown (the one that is selected by default each time the "Create flight" window is opened).

In this example I have A-10C at Ras Al airbase, and F/A-18 at CVN-71 Theodore Roosevelt. Liberation chooses aircraft in alphabetical order, so it picks A-10C from Ras Al. "Ras Al" is short > narrow dropdown > narrow window > CVN-71 gets cut off.

![01](https://user-images.githubusercontent.com/16318490/103189291-098add80-48dd-11eb-85b3-be8134e8b0ca.png)

![02](https://user-images.githubusercontent.com/16318490/103189329-3f2fc680-48dd-11eb-88d3-daaca302b605.png)

In the second example the A-10C has already been assigned, so this time Liberation picks the F/A-18. "CVN-71 Theodore Roosevelt" is long > wide dropdown > wide window.

![03](https://user-images.githubusercontent.com/16318490/103189367-66869380-48dd-11eb-8acb-1ebf6f63e420.png)

**Comment by DanAlbert** [comment]
Makes sense but not really sure why. At the very least we can just make the window big enough that it's never a problem. Probably less awkward than resizing the window based on the selected airfield anyway.

**Comment by dimkzr** [comment]
Yep, plenty of space there.

**Comment by Malakhit** [comment]
I believe I fixed this after it was raised on Discord. Marking as done.
